name: CI workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12, 14]

    name: Node.js ${{ matrix.node }}

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: S3cretP4ssw0rd!
        ports:
          - 1433:1433

    steps:
      - uses: actions/checkout@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: CI environment setup
      #   run: |
      #     curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      #     sudo apt-add-repository https://packages.microsoft.com/ubuntu/18.04/prod
      #     sudo apt-get update
      #     sudo apt-get install mssql-cli
      #     sudo apt-get install -f
      #     mssql-cli -S localhost -U sa -P S3cretP4ssw0rd! --query "CREATE DATABASE [fastify];"
      #     mssql-cli -S localhost -U sa -P S3cretP4ssw0rd! --query "CREATE TABLE [dbo].[users] ([id] bigint, [name] varchar, [email] varchar, PRIMARY KEY (id));"
      #     mssql-cli -S localhost -U sa -P S3cretP4ssw0rd! --query "INSERT INTO [dbo].[users] ([id], [name], [email]) VALUES ('1', N'foobar', N'foobar@gmail.com ');"
      #     mssql-cli -S localhost -U sa -P S3cretP4ssw0rd! --query "INSERT INTO [dbo].[users] ([id], [name], [email]) VALUES ('1', N'fizzbuzz', N'fizzbuzz@gmail.com ');"
      - name: Install
        run: npm install

      - name: Run tests
        run: npm run test

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v1
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{secrets.github_token}}
